In [ ]:
#SpendDNA
## Personal Transaction Analysis
# Name:Asothai D
# Batch:Data science/Data analytics program
# Date:8/10/2026

## Project Overview

SpendDNA is a personal transaction analysis project that uses Python and Pandas to clean, categorise, and analyse transaction data.

The project identifies spending patterns, monthly trends, time-of-day spending, unusual transactions, and the user's spending archetype.

## Dataset

The transaction dataset contains personal transaction records with details such as:

- Date
- Time
- Description
- Type
- Amount
- Balance
- Mode
- Reference

In [42]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [43]:
df = pd.read_csv("/content/rahul_transactions.csv")

print("Dataset loaded successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

Dataset loaded successfully!
Rows: 1328
Columns: 8

In [4]:
import zipfile
import os

zip_file = "/content/13750607-rahul_transactions.zip"

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall("/content")

print("ZIP extracted successfully!")
print(os.listdir("/content"))

ZIP extracted successfully!
['.config', '13750607-rahul_transactions.zip', 'SpendDNA_Minor_Project_Brief.pdf', 'rahul_transactions.csv', 'sample_data']

In [5]:
import os

print(os.listdir("/content"))

['.config', '13750607-rahul_transactions.zip', 'SpendDNA_Minor_Project_Brief.pdf', 'rahul_transactions.csv', 'sample_data']

In [6]:
import pandas as pd

df = pd.read_csv("/content/rahul_transactions.csv")

print("CSV loaded successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

df.head()

CSV loaded successfully!
Rows: 1328
Columns: 8

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   object
 1   Time         1328 non-null   object
 2   Description  1328 non-null   object
 3   Type         1328 non-null   object
 4   Amount       1328 non-null   object
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   object
 7   Ref          1328 non-null   object
dtypes: float64(1), object(7)
memory usage: 83.1+ KB

In [8]:
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [9]:
df.duplicated().sum()

np.int64(18)

In [10]:
df = df.drop_duplicates()

print("Duplicates removed!")
print("Rows remaining:", len(df))

Duplicates removed!
Rows remaining: 1310

In [11]:
print(df['Date'].head(10))

0     2024-01-01
1      01-Jan-24
2      01-Jan-24
3     2024-01-01
4    01 Jan 2024
5     2024-01-01
6     2024-01-01
7      01-Jan-24
8     2024-01-02
9       02/01/24
Name: Date, dtype: object

In [12]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

print("Date cleaning completed!")
print(df['Date'].head(10))

Date cleaning completed!
0   2024-01-01
1          NaT
2          NaT
3   2024-01-01
4          NaT
5   2024-01-01
6   2024-01-01
7          NaT
8   2024-02-01
9          NaT
Name: Date, dtype: datetime64[ns]

In [13]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

print("Date cleaning completed!")
print(df['Date'].head(10))

Date cleaning completed!
0   2024-01-01
1          NaT
2          NaT
3   2024-01-01
4          NaT
5   2024-01-01
6   2024-01-01
7          NaT
8   2024-02-01
9          NaT
Name: Date, dtype: datetime64[ns]

In [14]:
df.isnull().sum()

Date           1167
Time              0
Description       0
Type              0
Amount            0
Balance           0
Mode              0
Ref               0
dtype: int64

In [15]:
text_columns = ['Description', 'Type', 'Mode']

for col in text_columns:
    if col in df.columns:
        df[col] = df[col].fillna('Unknown')

print("Missing text values handled!")
print(df.isnull().sum())

Missing text values handled!
Date           1167
Time              0
Description       0
Type              0
Amount            0
Balance           0
Mode              0
Ref               0
dtype: int64

In [16]:
df['Type'].value_counts()

Type
DR       662
Debit    642
CR         6
Name: count, dtype: int64

In [17]:
df['Type'] = df['Type'].astype(str).str.strip().str.title()

print("Transaction Type cleaned!")
print(df['Type'].value_counts())

Transaction Type cleaned!
Type
Dr       662
Debit    642
Cr         6
Name: count, dtype: int64

In [18]:
df['Description'].head(20)

0                   AMAZON SELLER SVCS
1                            BHIM-BMTC
2     NEFT-TECHCRUSH LABS-SALARY MAY24
3                 UPI-AMAN-8934@OKAXIS
4                         BHIM-BLINKIT
5                           BHIM ZEPTO
6               UPI-UBER-2426@HDFCBANK
7                         BHIM-BLINKIT
8                 POS SWIGGY BANGALORE
9                UPI-GROWWPAY@HDFCBANK
10                        OLA ELECTRIC
11                   BMS MOVIE TICKETS
12                       POS OLA-PRIME
13                    SWIGGY-INSTAMART
14                  UPI-STARBUCKS@AXIS
15                UPI-THIRDWAVE@OKAXIS
16                    ANI Technologies
17                       BMTC BUS PASS
18                        POS TRUFFLES
19                      FLIPKART INDIA
Name: Description, dtype: object

In [19]:
def extract_vendor(description):
    text = str(description).upper()

    vendors = {
        'SWIGGY': 'Swiggy',
        'ZOMATO': 'Zomato',
        'ZEPTO': 'Zepto',
        'AMAZON': 'Amazon',
        'FLIPKART': 'Flipkart',
        'UBER': 'Uber',
        'OLA': 'Ola',
        'RAPIDO': 'Rapido',
        'NETFLIX': 'Netflix',
        'SPOTIFY': 'Spotify',
        'ZERODHA': 'Zerodha',
        'PHONEPE': 'PhonePe',
        'GPAY': 'Google Pay',
        'GOOGLE PAY': 'Google Pay',
        'PAYTM': 'Paytm'
    }

    for key, vendor in vendors.items():
        if key in text:
            return vendor

    return 'Uncategorised'


df['Vendor'] = df['Description'].apply(extract_vendor)

print(df[['Description', 'Vendor']].head(20))

                         Description         Vendor
0                 AMAZON SELLER SVCS         Amazon
1                          BHIM-BMTC  Uncategorised
2   NEFT-TECHCRUSH LABS-SALARY MAY24  Uncategorised
3               UPI-AMAN-8934@OKAXIS  Uncategorised
4                       BHIM-BLINKIT  Uncategorised
5                         BHIM ZEPTO          Zepto
6             UPI-UBER-2426@HDFCBANK           Uber
7                       BHIM-BLINKIT  Uncategorised
8               POS SWIGGY BANGALORE         Swiggy
9              UPI-GROWWPAY@HDFCBANK  Uncategorised
10                      OLA ELECTRIC            Ola
11                 BMS MOVIE TICKETS  Uncategorised
12                     POS OLA-PRIME            Ola
13                  SWIGGY-INSTAMART         Swiggy
14                UPI-STARBUCKS@AXIS  Uncategorised
15              UPI-THIRDWAVE@OKAXIS  Uncategorised
16                  ANI Technologies  Uncategorised
17                     BMTC BUS PASS  Uncategorised
18                      POS TRUFFLES  Uncategorised
19                    FLIPKART INDIA       Flipkart

In [20]:
vendor_counts = df['Vendor'].value_counts()

print(vendor_counts)

Vendor
Uncategorised    580
Swiggy           196
Zomato           121
Uber              71
Amazon            70
Ola               69
Zepto             58
Flipkart          43
Rapido            41
Paytm             29
Zerodha           14
Netflix           10
Spotify            8
Name: count, dtype: int64

In [21]:
print("Top 10 Vendors")
print(df['Vendor'].value_counts().head(10))

Top 10 Vendors
Vendor
Uncategorised    580
Swiggy           196
Zomato           121
Uber              71
Amazon            70
Ola               69
Zepto             58
Flipkart          43
Rapido            41
Paytm             29
Name: count, dtype: int64

In [22]:
def assign_category(row):
    text = str(row['Description']).upper()
    vendor = str(row['Vendor']).upper()

    if vendor in ['SWIGGY', 'ZOMATO']:
        return 'Food & Dining'
    elif vendor == 'ZEPTO':
        return 'Groceries'
    elif vendor in ['AMAZON', 'FLIPKART']:
        return 'Shopping'
    elif vendor in ['UBER', 'OLA', 'RAPIDO']:
        return 'Transport'
    elif vendor in ['NETFLIX', 'SPOTIFY']:
        return 'Entertainment'
    elif vendor == 'ZERODHA':
        return 'Investments'
    elif any(word in text for word in ['RENT', 'HOUSE RENT']):
        return 'Rent'
    elif any(word in text for word in ['ELECTRICITY', 'EB', 'WATER', 'BILL']):
        return 'Bills & Utilities'
    elif any(word in text for word in ['HOSPITAL', 'PHARMACY', 'MEDICAL']):
        return 'Healthcare'
    elif any(word in text for word in ['TRANSFER', 'NEFT', 'IMPS']):
        return 'Personal Transfer'
    else:
        return 'Other'


df['Category'] = df.apply(assign_category, axis=1)

print(df[['Description', 'Vendor', 'Category']].head(20))

                         Description         Vendor           Category
0                 AMAZON SELLER SVCS         Amazon           Shopping
1                          BHIM-BMTC  Uncategorised              Other
2   NEFT-TECHCRUSH LABS-SALARY MAY24  Uncategorised  Personal Transfer
3               UPI-AMAN-8934@OKAXIS  Uncategorised              Other
4                       BHIM-BLINKIT  Uncategorised              Other
5                         BHIM ZEPTO          Zepto          Groceries
6             UPI-UBER-2426@HDFCBANK           Uber          Transport
7                       BHIM-BLINKIT  Uncategorised              Other
8               POS SWIGGY BANGALORE         Swiggy      Food & Dining
9              UPI-GROWWPAY@HDFCBANK  Uncategorised              Other
10                      OLA ELECTRIC            Ola          Transport
11                 BMS MOVIE TICKETS  Uncategorised              Other
12                     POS OLA-PRIME            Ola          Transport
13                  SWIGGY-INSTAMART         Swiggy      Food & Dining
14                UPI-STARBUCKS@AXIS  Uncategorised              Other
15              UPI-THIRDWAVE@OKAXIS  Uncategorised              Other
16                  ANI Technologies  Uncategorised              Other
17                     BMTC BUS PASS  Uncategorised              Other
18                      POS TRUFFLES  Uncategorised              Other
19                    FLIPKART INDIA       Flipkart           Shopping

In [23]:
category_spending = (
    df[df['Type'] == 'Debit']
    .groupby('Category')['Amount']
    .sum()
    .sort_values(ascending=False)
)

print("Category-wise Spending")
print(category_spending)

Category-wise Spending
Category
Shopping             ₹24624208Rs. 2,814Rs. 4,092Rs. 558Rs. 4,473103...
Other                ₹1828270.00₹482₹311266.00267.00Rs. 48₹1411878....
Bills & Utilities    ₹1768Rs. 1,3661107₹2240₹491₹168923943,628.00Rs...
Food & Dining        Rs. 537₹571₹238Rs. 438₹407267.00442535₹468₹240...
Investments          Rs. 15,000Rs. 15,0001500015,000.001500015000Rs...
Transport            Rs. 148₹350₹439284.00351.00Rs. 461₹283115.0015...
Groceries            527.00610778.00417.00500.00Rs. 617₹711717.00₹5...
Entertainment           334.00119119210.00₹600Rs. 119419Rs. 626Rs. 596
Rent                      18,000.00Rs. 18,000Rs. 18,00018,000.00₹18000
Name: Amount, dtype: object

In [26]:
print(df['Type'].unique())

['Debit' 'Dr' 'Cr']

In [28]:
print(df.columns.tolist())

['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref', 'Vendor', 'Category']

In [30]:
df['Month'] = df['Date'].dt.strftime('%b')

monthly_spending = (
    df[df['Type'].str.lower() == 'debit']
    .groupby('Month')['Amount']
    .sum()
)

print("===== MONTHLY SPENDING =====")
print(monthly_spending)

===== MONTHLY SPENDING =====
Month
Apr                                Rs. 4473,311.00632.00
Aug                                 Rs. 475₹282₹4496₹431
Dec                                      1266₹910Rs. 377
Feb                     Rs. 537267.00453697235996Rs. 685
Jan    ₹2462₹1828Rs. 148791.00606.00169.00₹292Rs. 1,7...
Jul                       442351.00₹842₹413₹56215000₹592
Jun                              442₹30001,860.00Rs. 481
Mar                      ₹439₹2382,147.00512169.00₹18000
May                              502₹43118,000.00Rs. 218
Nov                              259.00Rs. 376₹680433500
Oct                                599387420.00Rs. 1,344
Sep                      527.00318.00210.00214394Rs. 246
Name: Amount, dtype: object

In [31]:
df['Hour'] = pd.to_numeric(
    df['Time'].astype(str).str[:2],
    errors='coerce'
)

def time_period(hour):
    if pd.isna(hour):
        return 'Unknown'
    elif hour < 6:
        return 'Late Night'
    elif hour < 12:
        return 'Morning'
    elif hour < 17:
        return 'Afternoon'
    elif hour < 21:
        return 'Evening'
    else:
        return 'Night'

df['Time_Period'] = df['Hour'].apply(time_period)

time_spending = (
    df[df['Type'].str.lower() == 'debit']
    .groupby('Time_Period')['Amount']
    .sum()
    .sort_values(ascending=False)
)

print("===== TIME-OF-DAY SPENDING =====")
print(time_spending)

===== TIME-OF-DAY SPENDING =====
Time_Period
Night         ₹482Rs. 48₹439₹2387531,641.001266₹229Rs. 15,00...
Morning       ₹350₹311420850218,000.00Rs. 3297,314.00Rs. 15,...
Late Night    ₹2462Rs. 537₹14111639Rs. 438640₹316334.00Rs. 5...
Afternoon     ₹1828270.00Rs. 148₹571266.00₹2314Rs. 447284.00...
Evening       267.00878.00267.00442351.00Rs. 461₹46861033.00...
Name: Amount, dtype: object

In [34]:
df['Amount'] = (
    df['Amount']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace('Rs.', '', regex=False)
    .str.replace('Rs', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')

print("Amount converted successfully!")
print(df['Amount'].dtype)
print(df['Amount'].head())

Amount converted successfully!
float64
0     2462.0
1       50.0
2    84728.0
3     1828.0
4      270.0
Name: Amount, dtype: float64

In [35]:
# AI-assisted: basic debugging and z-score calculation syntax.

debit_df = df[df['Type'].astype(str).str.strip().str.lower() == 'debit'].copy()

category_mean = debit_df.groupby('Category')['Amount'].transform('mean')
category_std = debit_df.groupby('Category')['Amount'].transform('std')

category_std = category_std.replace(0, pd.NA)

debit_df['Z_Score'] = (
    (debit_df['Amount'] - category_mean) / category_std
)

anomalies = debit_df[debit_df['Z_Score'] > 2].copy()

print("===== TOP ANOMALIES =====")
print(
    anomalies[
        ['Date', 'Description', 'Category', 'Amount', 'Z_Score']
    ]
    .sort_values('Z_Score', ascending=False)
    .head(10)
)

===== TOP ANOMALIES =====
     Date               Description  Category   Amount   Z_Score
971   NaT       UPI-MYNTRA@HDFCBANK     Other  11565.0  6.922953
1007  NaT            MYNTRA DESIGNS     Other  11391.0  6.807679
1271  NaT               POS DINEOUT     Other   7935.0  4.518091
749   NaT  POS INDIAN OIL BANGALORE     Other   7828.0  4.447203
49    NaT  POS BANGALORE RESTAURANT     Other   7314.0   4.10668
148   NaT      UPI-IOC9075@HDFCBANK     Other   7264.0  4.073555
269   NaT    UPI-AMAZONPAY@HDFCBANK  Shopping  21986.0  3.419126
475   NaT    UPI-AMAZONPAY@HDFCBANK  Shopping  19917.0  3.026676
450   NaT                 AMAZON IN  Shopping  18273.0  2.714839
499   NaT          ATM-WDL-SBI-4080     Other   5000.0  2.573663

In [36]:
# AI-assisted: rule-based archetype classification syntax.

debit_df = df[
    df['Type'].astype(str).str.strip().str.lower() == 'debit'
].copy()

category_spending = (
    debit_df.groupby('Category')['Amount']
    .sum()
    .sort_values(ascending=False)
)

total_spending = debit_df['Amount'].sum()

top_category = category_spending.index[0]
top_percentage = (category_spending.iloc[0] / total_spending) * 100

late_night_spending = debit_df[
    debit_df['Time_Period'].isin(['Late Night', 'Night'])
]['Amount'].sum()

late_night_percentage = (
    late_night_spending / total_spending
) * 100

print("===== SPENDING ARCHETYPE =====")
print("Top Category:", top_category)
print(f"Top Category Share: {top_percentage:.2f}%")
print(f"Late Night/Night Spending: {late_night_percentage:.2f}%")

if top_category == 'Food & Dining':
    archetype = 'Foodie'
elif top_category == 'Shopping':
    archetype = 'Shopaholic'
elif top_category == 'Transport':
    archetype = 'Cab Commuter'
elif top_category == 'Entertainment':
    archetype = 'Subscription Lover'
elif top_category == 'Investments':
    archetype = 'Investor'
else:
    archetype = 'Balanced Spender'

print("Spending Archetype:", archetype)

===== SPENDING ARCHETYPE =====
Top Category: Other
Top Category Share: 36.53%
Late Night/Night Spending: 23.44%
Spending Archetype: Balanced Spender

In [38]:
# AI-assisted: final report formatting and summary syntax.

print("=" * 50)
print("              SpendDNA FINAL REPORT")
print("=" * 50)

print(f"Total Transactions : {len(df)}")
print(f"Total Spending    : ₹{debit_df['Amount'].sum():,.2f}")
print(f"Total Income      : ₹{df[df['Type'].astype(str).str.lower() == 'credit']['Amount'].sum():,.2f}")

print("\nTop 5 Spending Categories:")
print(category_spending.head(5))

print("\nTop Vendors:")
print(df['Vendor'].value_counts().head(5))

print("\nTop Anomalies:")
print(
    anomalies[['Description', 'Category', 'Amount', 'Z_Score']]
    .sort_values('Z_Score', ascending=False)
    .head(5)
)

print("\nSpending Archetype:", archetype)

print("\n===== 3 DATA-SPECIFIC INSIGHTS =====")

print(f"1. The highest spending category is {top_category}, contributing {top_percentage:.2f}% of total debit spending.")

print(f"2. Late Night/Night transactions contribute {late_night_percentage:.2f}% of total spending.")

print(f"3. The detected spending archetype is {archetype} based on the user's spending pattern.")

print("=" * 50)

==================================================
              SpendDNA FINAL REPORT
==================================================
Total Transactions : 1310
Total Spending    : ₹857,855.00
Total Income      : ₹0.00

Top 5 Spending Categories:
Category
Other            313373.0
Shopping         225741.0
Investments      105000.0
Rent              90000.0
Food & Dining     66236.0
Name: Amount, dtype: float64

Top Vendors:
Vendor
Uncategorised    580
Swiggy           196
Zomato           121
Uber              71
Amazon            70
Name: count, dtype: int64

Top Anomalies:
                   Description Category   Amount   Z_Score
971        UPI-MYNTRA@HDFCBANK    Other  11565.0  6.922953
1007            MYNTRA DESIGNS    Other  11391.0  6.807679
1271               POS DINEOUT    Other   7935.0  4.518091
749   POS INDIAN OIL BANGALORE    Other   7828.0  4.447203
49    POS BANGALORE RESTAURANT    Other   7314.0   4.10668

Spending Archetype: Balanced Spender

===== 3 DATA-SPECIFIC INSIGHTS =====
1. The highest spending category is Other, contributing 36.53% of total debit spending.
2. Late Night/Night transactions contribute 23.44% of total spending.
3. The detected spending archetype is Balanced Spender based on the user's spending pattern.
==================================================

In [40]:
print("SpendDNA Final Reflection")
print("I learned how to clean, analyse and understand transaction data using Python and Pandas.")
print("I learned vendor extraction, category tagging, spending analysis and anomaly detection.")
print("This project improved my Python and data analysis skills.")

SpendDNA Final Reflection
I learned how to clean, analyse and understand transaction data using Python and Pandas.
I learned vendor extraction, category tagging, spending analysis and anomaly detection.
This project improved my Python and data analysis skills.

In [41]:
print("""
# SpendDNA

## Project Overview
SpendDNA is a personal transaction analysis project built using Python and Pandas.

## Features
- Transaction Parser
- Vendor Extractor
- Category Tagger
- Spending Overview
- Monthly Trend Analysis
- Time-of-Day Analysis
- Anomaly Detection
- Spending Archetype Detection

## Tools Used
- Python
- Pandas
- NumPy
- Google Colab

## Conclusion
This project helped me understand how transaction data can be cleaned,
categorised and analysed to identify meaningful spending patterns.
""")

# SpendDNA

## Project Overview
SpendDNA is a personal transaction analysis project built using Python and Pandas.

## Features
- Transaction Parser
- Vendor Extractor
- Category Tagger
- Spending Overview
- Monthly Trend Analysis
- Time-of-Day Analysis
- Anomaly Detection
- Spending Archetype Detection

## Tools Used
- Python
- Pandas
- NumPy
- Google Colab

## Conclusion
This project helped me understand how transaction data can be cleaned,
categorised and analysed to identify meaningful spending patterns.